[build]
  command = "npm run build"
  publish = "dist"
  base = "/Crypto_Dashboard/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 